Auto nav code in Protobot
Team293/RapidReact pull request #21
Opened 2022-02-14 21:25 UTC by cartha353

placed all of the Octabot code in to Protobot.

2022-02-14 21:26 UTC, lillaantal1 approved these changes

2022-02-14 21:26 UTC, mahisvivemulapalli approved these changes
looks good

2022-02-14 21:29 UTC, NinaPlazonic approved these changes

2022-02-19 17:47 UTC, bjmcternan approved these changes
Some very minor cleanup things that we can get another time. This looks good to me

2022-02-19 17:47 UTC, bjmcternan commented on src/main/java/frc/robot/classes/SmoothControl.java
> +    double k = k(range, thetaT, del_r);
I'm not a fan of the variable name and function being the same. I did not realize this at the time. We can fix it later

2022-02-19 18:43 UTC, bjmcternan requested changes
What were those changes?

2022-02-19 18:46 UTC, BobTheLegend commented
> What were those changes?

The autonav code had previously been untested so when testing it I found 2 null pointers as the kinematics and NavX had not been instantiated. In addition, there was a small change in the constants file where a rogue bracket screwed some things up.

2022-02-19 19:33 UTC, bjmcternan approved these changes

2022-02-19 19:38 UTC, PranjalMhetre approved these changes

2022-02-20 15:58 UTC, merged