Climb
Team293/RapidReact pull request #52
Opened 2022-03-16 22:03 UTC by KaiFrc

# Purpose: Created climb functionality for the robot. Tested and climbs as intended to the middle rung.
## Files Changed...

Climb.java: Climb Subsystem
RetractClimb.java: Command that retracts solenoid
ExtendClimb.java: Command that extends solenoid
Constants.java:  Added necessary pneumatic/climber constants for easier readability
RobotContainer.java: Controller info

2022-03-17 15:07 UTC, bjmcternan requested changes
This PR looks OK functionally, but it needs to be cleaned up

2022-03-17 15:07 UTC, bjmcternan commented on src/main/java/frc/robot/RobotContainer.java
> +
Extra whitespace

2022-03-17 15:07 UTC, bjmcternan commented on src/main/java/frc/robot/commands/ExtendClimb.java
> +
Extra whitespace. We can also remove the auto generated comments

2022-03-17 15:07 UTC, bjmcternan commented on src/main/java/frc/robot/commands/ExtendClimb.java
> +
Extra whitespace. We can also remove the auto generated comments

2022-03-17 15:07 UTC, bjmcternan commented on src/main/java/frc/robot/commands/RetractClimb.java
> +
Extra whitespace. We can also remove the auto generated comments

2022-03-17 15:07 UTC, bjmcternan commented on src/main/java/frc/robot/commands/RetractClimb.java
> +
In fact, this file needs to be cleaned up

2022-03-17 15:07 UTC, bjmcternan commented on src/main/java/frc/robot/subsystems/Climb.java
> +    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
Cleanup this file. Remove extra whitespace and auto generated comments

2022-03-17 19:50 UTC, KaiFrc commented
We're using one double solenoid instead of two now, same. cleaned the code.

2022-03-17 22:41 UTC, bjmcternan requested changes
Let's merge main into this first. The constants file are going to have conflicts.

2022-03-17 23:56 UTC, KaiFrc commented
I merged the main file into climb yesterday. It should go through

2022-03-18 00:03 UTC, bjmcternan commented
There's stuff on the other PRs that is about to go in which will cause conflicts. 

1. Launcher PR
2. Emoji removal PR
3. This PR

2022-03-18 00:06 UTC, KaiFrc commented
Do you suggest we merge the other PRS first and then merge this PR into main?

2022-03-18 00:12 UTC, KaiFrc commented
I successfully merged the other PRS and resolved the merging fixes, awaiting approval.

2022-03-18 00:15 UTC, bjmcternan commented
Oops one sec

2022-03-18 00:15 UTC, KaiFrc commented
Accidentily closed instead of comment MB

2022-03-18 00:23 UTC, bjmcternan approved these changes
Don't break the launcher. That PR needs to go in now

2022-03-18 00:28 UTC, merged

2022-03-18 00:28 UTC, bjmcternan requested changes
Hold on this changes constants that cannot change