Merging Tested Competition Changes into Main
Team293/RapidReact pull request #57
Opened 2022-03-22 13:52 UTC by BobTheLegend

The sum of all the changes made at the competition to create a somewhat competitive robot (Yay!)

Includes:
Fixes to belt motor problems observed before
A manual override to team color as FMS was not acting as expected
A max shooter RPM to cap the speed
Changes in camera light logic reflect the fact that nobody cared about the rules
Addition of several manual commands for use if the main "Fire" command failed
Somewhat arbitrary alterations to several constants
A new limelight ty -> RPM regression that kinda works
A cannibalized but working auto

2022-03-22 14:19 UTC, bjmcternan requested changes
Some formatting issues and things that needs explaining

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/RobotContainer.java
> +    // Lower the launcher pistonc
Typo

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/RobotContainer.java
> +
Extra newline

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/RobotContainer.java
> +        startingPosition = StartPositions.BLUE_MIDDLE;
Let's not change these. If we need to force a start position we can do it on line 119. Something like this:

```
public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    // When either the alliance colour check or the location check fails it defaults
    // to the blue left side
    Command autoCommand = null;
    Alliance allianceColor = DriverStation.getAlliance();
    locationNumber = DriverStation.getLocation();


    StartPositions startingPosition = StartPositions.INVALID;

    //Force Alliance Color
   allianceColor = Alliance.Blue;

    //Force Location
    locationNumber = 2;

    if (allianceColor == Alliance.Blue) {
      if (locationNumber  == 1) {
        startingPosition = StartPositions.BLUE_MIDDLE;
      } else if (locationNumber  == 2) {
        startingPosition = StartPositions.BLUE_MIDDLE;
      } else if (locationNumber  == 3) {
        startingPosition = StartPositions.BLUE_MIDDLE;
      }
    } else if (allianceColor == Alliance.Red) {
      if (locationNumber  == 1) {
        startingPosition = StartPositions.BLUE_MIDDLE;
      } else if (locationNumber  == 2) {
        startingPosition = StartPositions.BLUE_MIDDLE;
      } else if (locationNumber  == 3) {
        startingPosition = StartPositions.BLUE_MIDDLE;
      }
    } else {
      System.out.println("WARNING - Invalid alliance color! [" + allianceColor + "]");
    }

    if (StartPositions.INVALID == startingPosition) {
      System.out.println("WARNING - Invalid starting position! [" + startingPosition + "]");
    } else {
      autoCommand = new SequentialAutoCommand(m_drivetrain, m_kinematics, m_feeder, m_targeting, m_launcher,
          startingPosition, m_climb);
    }

    return autoCommand;
  }
```

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/RobotContainer.java
> +          startingPosition, m_climb);
Why is m_climb needed? For the compressor?

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/BallControl.java
> +
Extra newline

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/DisableLimelight.java
> +
Extra newline

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/DisableLimelight.java
> +
Extra newline

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/EnableLimelight.java
> +
Extra newline

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/EnableLimelight.java
> +
Extra newline

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/Fire.java
> +        // if (true == DriverStation.getAlliance().equals(Alliance.Blue)) {
Why comment this out? Was the FMS not working during the competition on Saturday/Sunday?

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/Fire.java
> +
Extra newline

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/ForceDump.java
> +
Extra newline

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/ForceDump.java
> +
Extra newline

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/ForceDump.java
> +
Extra newline

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/ForceDump.java
> +        // if (true == DriverStation.getAlliance().equals(Alliance.Blue)) {
If this is not needed, let's remove the commented out code

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/ForceDump.java
> +
Extra newline

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/Rotate.java
> +import static frc.robot.Constants.DrivetrainConstants.*;
Let's not grab every constant. Can we just grab the drivetrain constants instead?

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/SequentialAutoCommand.java
> +
replace this Extra newline with a comment

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/SequentialAutoCommand.java
> +                    // new ParallelRaceGroup(
Let's remove this if it is not needed

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/commands/Wait.java
> +
Extra newline

2022-03-22 14:19 UTC, bjmcternan commented on src/main/java/frc/robot/subsystems/Targeting.java
> +            // if(ty > 6.7){
Let's remove the commented out code if it is not needed anymore

2022-03-25 23:23 UTC, cartha353 commented
The relevant parts of this code have been brought in DistanceToRPM which will have another PR

2022-03-25 23:23 UTC, closed without merging